language: node_js
# At this time, the travis trusty sudo environment works, but the sudo: false
# environment doesn't (it might with a bunch of apt packages).
sudo: required
dist: trusty

node_js:
  - 4

addons:
  firefox: latest  # version 55.0 - 57.x have an issue with screenshots.
  # firefox: 54.0.1
  chrome: stable
  apt:
    packages:
      # I suspect that not all of these are necessary
      - mesa-utils
      - xvfb
      - libosmesa6

      - libgif-dev
      - libpng-dev

      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libxxf86vm-dev
      - libxrandr-dev

      - optipng

cache:
  directories:
    - node_modules
    - "$HOME/cache"

before_install:
  # Start xvfb with a specific resolution and pixel depth
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - CACHE="${HOME}/cache" CMAKE_VERSION=3.5.0 CMAKE_SHORT_VERSION=3.5 source ./scripts/install_cmake.sh
  - npm prune
  - npm install -g npm

before_script:
  - export DISPLAY=:99.0
  # Report on available GL support
  - glxinfo

script:
  - npm run build
  - npm run docs
  - mkdir _build
  - ctest -S cmake/travis_build.cmake -VV || true
  - if [ -f _build/test_failed ] ; then false ; fi

after_failure:
  # Upload test results.  First make them smaller with optipng.
  - pip install --user --upgrade girder-client requests[security]
  - find _build/images -name '*-test.png' -exec optipng {} \+
  - find _build/images -name '*-test.png' -exec python scripts/upload_test_images.py {} \+

after_success:
  - npm run codecov
  - pip install --user GitPython boto3
  - python $TRAVIS_BUILD_DIR/scripts/upload_notes.py --repo $TRAVIS_BUILD_DIR --upload $TRAVIS_BUILD_DIR/_build/build_notes.json

env:
  global:
    - secure: JYWs3zJV09uAb7CvX32pADRYTH2XqSGvImNEI6zVFxJxs9r0JsGgyOTz4PPBgs3dv1OjVBXqxu4GD2ZBKeo0Ax13ZnBNVR/BacupBtIwXbxp/FG2lr+WBzE0YnEBhAF/mW5DEkNBWJyLSiBlxYA5QFAAHYwb/GOADl+Z9Qi2FIU=
    - secure: on13Ka+3jkLDCXxqzxuT+CY4sPM0Zxfbe9M2F3LE0yhN2ww5vaBKdbTrzEWa0TOlBkM2qQUPAFybjHXfHeRyKpZDlsssjogH8YO5qx4zFRP5ZB9ny39QAqBsfZTuXt2WmOTLEcXkByYXVH8my/8ZqZqofSeBZsZdeauzoLbr0R0=
